/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConceptValueSetMembershipId generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlRootElement
@XmlType(namespace="de.fhdo.termserver.types")
@Embeddable
public class ConceptValueSetMembershipId  implements java.io.Serializable {


     private Long codeSystemEntityVersionId;
     private Long valuesetVersionId;

    public ConceptValueSetMembershipId() {
    }

    public ConceptValueSetMembershipId(Long codeSystemEntityVersionId, Long valuesetVersionId) {
       this.codeSystemEntityVersionId = codeSystemEntityVersionId;
       this.valuesetVersionId = valuesetVersionId;
    }
   

    @Column(name="codeSystemEntityVersionId", nullable=false)
    public Long getCodeSystemEntityVersionId() {
        return this.codeSystemEntityVersionId;
    }
    
    public void setCodeSystemEntityVersionId(Long codeSystemEntityVersionId) {
        this.codeSystemEntityVersionId = codeSystemEntityVersionId;
    }

    @Column(name="valuesetVersionId", nullable=false)
    public Long getValuesetVersionId() {
        return this.valuesetVersionId;
    }
    
    public void setValuesetVersionId(Long valuesetVersionId) {
        this.valuesetVersionId = valuesetVersionId;
    }


     @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConceptValueSetMembershipId) ) return false;
		 ConceptValueSetMembershipId castOther = ( ConceptValueSetMembershipId ) other; 
         
		 return (this.getCodeSystemEntityVersionId()==castOther.getCodeSystemEntityVersionId())
 && (this.getValuesetVersionId()==castOther.getValuesetVersionId());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) ((long)this.getCodeSystemEntityVersionId());
         result = 37 * result + (int) ((long)this.getValuesetVersionId());
         return result;
   }   


}


