package de.fhdo.collaboration.db.classes;
// Generated 30.06.2015 09:32:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name="file"
    
)
public class File  implements java.io.Serializable {


     private long linkId;
     private byte[] data;

    public File() {
    }

	
    public File(long linkId) {
        this.linkId = linkId;
    }
    public File(long linkId, byte[] data) {
       this.linkId = linkId;
       this.data = data;
    }
   
     @Id 

    
    @Column(name="link_id", unique=true, nullable=false)
    public long getLinkId() {
        return this.linkId;
    }
    
    public void setLinkId(long linkId) {
        this.linkId = linkId;
    }

    
    @Column(name="data")
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }




}


