/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Discussiongroupobject generated by hbm2java
 */
@Entity
@Table(name="discussiongroupobject"
    
)
public class Discussiongroupobject  implements java.io.Serializable {


     private Long id;
     private Discussiongroup discussiongroup;
     private String classname;
     private Long classId;

    public Discussiongroupobject() {
    }

    public Discussiongroupobject(Long id, Discussiongroup discussiongroup, String classname, Long classId) {
       this.id = id;
       this.discussiongroup = discussiongroup;
       this.classname = classname;
       this.classId = classId;
    }
   
    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionGroup_id", nullable=false)
    public Discussiongroup getDiscussiongroup() {
        return this.discussiongroup;
    }
    
    public void setDiscussiongroup(Discussiongroup discussiongroup) {
        this.discussiongroup = discussiongroup;
    }
    
    @Column(name="classname", nullable=false, length=65535)
    public String getClassname() {
        return this.classname;
    }
    
    public void setClassname(String classname) {
        this.classname = classname;
    }
    
    @Column(name="classId", nullable=false)
    public Long getClassId() {
        return this.classId;
    }
    
    public void setClassId(Long classId) {
        this.classId = classId;
    }
}