package de.fhdo.collaboration.db.classes;
// Generated 30.06.2015 09:32:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DomainValue generated by hbm2java
 */
@Entity
@Table(name="domain_value"
    
)
public class DomainValue  implements java.io.Serializable {


     private Long id;
     private Domain domain;
     private String code;
     private String displayText;
     private String description;
     private String attrib1;
     private String attrib2;
     private String attrib3;
     private Integer orderNo;
     private String imageFile;
     private long languageId;
     private Set<Domain> domainsForDefaultValueId = new HashSet<Domain>(0);
     private Set<Domain> domainsForDisplayOrder = new HashSet<Domain>(0);
     private Set<SysParam> sysParamsForModifyLevel = new HashSet<SysParam>(0);
     private Set<DomainValue> domainValuesForDomainValueIdParent = new HashSet<DomainValue>(0);
     private Set<DomainValue> domainValuesForDomainValueIdChild = new HashSet<DomainValue>(0);
     private Set<SysParam> sysParamsForValidityDomain = new HashSet<SysParam>(0);

    public DomainValue() {
    }

	
    public DomainValue(Domain domain, String code, long languageId) {
        this.domain = domain;
        this.code = code;
        this.languageId = languageId;
    }
    public DomainValue(Domain domain, String code, String displayText, String description, String attrib1, String attrib2, String attrib3, Integer orderNo, String imageFile, long languageId, Set<Domain> domainsForDefaultValueId, Set<Domain> domainsForDisplayOrder, Set<SysParam> sysParamsForModifyLevel, Set<DomainValue> domainValuesForDomainValueIdParent, Set<DomainValue> domainValuesForDomainValueIdChild, Set<SysParam> sysParamsForValidityDomain) {
       this.domain = domain;
       this.code = code;
       this.displayText = displayText;
       this.description = description;
       this.attrib1 = attrib1;
       this.attrib2 = attrib2;
       this.attrib3 = attrib3;
       this.orderNo = orderNo;
       this.imageFile = imageFile;
       this.languageId = languageId;
       this.domainsForDefaultValueId = domainsForDefaultValueId;
       this.domainsForDisplayOrder = domainsForDisplayOrder;
       this.sysParamsForModifyLevel = sysParamsForModifyLevel;
       this.domainValuesForDomainValueIdParent = domainValuesForDomainValueIdParent;
       this.domainValuesForDomainValueIdChild = domainValuesForDomainValueIdChild;
       this.sysParamsForValidityDomain = sysParamsForValidityDomain;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="domain_id", nullable=false)
    public Domain getDomain() {
        return this.domain;
    }
    
    public void setDomain(Domain domain) {
        this.domain = domain;
    }

    
    @Column(name="code", nullable=false, length=30)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="display_text", length=65535)
    public String getDisplayText() {
        return this.displayText;
    }
    
    public void setDisplayText(String displayText) {
        this.displayText = displayText;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="attrib1", length=60)
    public String getAttrib1() {
        return this.attrib1;
    }
    
    public void setAttrib1(String attrib1) {
        this.attrib1 = attrib1;
    }

    
    @Column(name="attrib2", length=60)
    public String getAttrib2() {
        return this.attrib2;
    }
    
    public void setAttrib2(String attrib2) {
        this.attrib2 = attrib2;
    }

    
    @Column(name="attrib3", length=60)
    public String getAttrib3() {
        return this.attrib3;
    }
    
    public void setAttrib3(String attrib3) {
        this.attrib3 = attrib3;
    }

    
    @Column(name="order_no")
    public Integer getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    
    @Column(name="image_file", length=65535)
    public String getImageFile() {
        return this.imageFile;
    }
    
    public void setImageFile(String imageFile) {
        this.imageFile = imageFile;
    }

    
    @Column(name="language_id", nullable=false)
    public long getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(long languageId) {
        this.languageId = languageId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="domainValueByDefaultValueId")
    public Set<Domain> getDomainsForDefaultValueId() {
        return this.domainsForDefaultValueId;
    }
    
    public void setDomainsForDefaultValueId(Set<Domain> domainsForDefaultValueId) {
        this.domainsForDefaultValueId = domainsForDefaultValueId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="domainValueByDisplayOrder")
    public Set<Domain> getDomainsForDisplayOrder() {
        return this.domainsForDisplayOrder;
    }
    
    public void setDomainsForDisplayOrder(Set<Domain> domainsForDisplayOrder) {
        this.domainsForDisplayOrder = domainsForDisplayOrder;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="domainValueByModifyLevel")
    public Set<SysParam> getSysParamsForModifyLevel() {
        return this.sysParamsForModifyLevel;
    }
    
    public void setSysParamsForModifyLevel(Set<SysParam> sysParamsForModifyLevel) {
        this.sysParamsForModifyLevel = sysParamsForModifyLevel;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="domainvalue2domainvalue", joinColumns = { 
        @JoinColumn(name="domain_value_id_child", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="domain_value_id_parent", nullable=false, updatable=false) })
    public Set<DomainValue> getDomainValuesForDomainValueIdParent() {
        return this.domainValuesForDomainValueIdParent;
    }
    
    public void setDomainValuesForDomainValueIdParent(Set<DomainValue> domainValuesForDomainValueIdParent) {
        this.domainValuesForDomainValueIdParent = domainValuesForDomainValueIdParent;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="domainvalue2domainvalue", joinColumns = { 
        @JoinColumn(name="domain_value_id_parent", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="domain_value_id_child", nullable=false, updatable=false) })
    public Set<DomainValue> getDomainValuesForDomainValueIdChild() {
        return this.domainValuesForDomainValueIdChild;
    }
    
    public void setDomainValuesForDomainValueIdChild(Set<DomainValue> domainValuesForDomainValueIdChild) {
        this.domainValuesForDomainValueIdChild = domainValuesForDomainValueIdChild;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="domainValueByValidityDomain")
    public Set<SysParam> getSysParamsForValidityDomain() {
        return this.sysParamsForValidityDomain;
    }
    
    public void setSysParamsForValidityDomain(Set<SysParam> sysParamsForValidityDomain) {
        this.sysParamsForValidityDomain = sysParamsForValidityDomain;
    }




}


