package de.fhdo.collaboration.db.classes;
// Generated 30.06.2015 09:32:45 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name="link"
    
)
public class Link  implements java.io.Serializable {


     private Long id;
     private Collaborationuser collaborationuser;
     private Discussion discussion;
     private Proposal proposal;
     private String content;
     private Date insertTs;
     private String description;
     private Integer linkType;
     private String mimeType;

    public Link() {
    }

	
    public Link(Collaborationuser collaborationuser, Date insertTs) {
        this.collaborationuser = collaborationuser;
        this.insertTs = insertTs;
    }
    public Link(Collaborationuser collaborationuser, Discussion discussion, Proposal proposal, String content, Date insertTs, String description, Integer linkType, String mimeType) {
       this.collaborationuser = collaborationuser;
       this.discussion = discussion;
       this.proposal = proposal;
       this.content = content;
       this.insertTs = insertTs;
       this.description = description;
       this.linkType = linkType;
       this.mimeType = mimeType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="collaborationUserId", nullable=false)
    public Collaborationuser getCollaborationuser() {
        return this.collaborationuser;
    }
    
    public void setCollaborationuser(Collaborationuser collaborationuser) {
        this.collaborationuser = collaborationuser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionId")
    public Discussion getDiscussion() {
        return this.discussion;
    }
    
    public void setDiscussion(Discussion discussion) {
        this.discussion = discussion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proposalId")
    public Proposal getProposal() {
        return this.proposal;
    }
    
    public void setProposal(Proposal proposal) {
        this.proposal = proposal;
    }

    
    @Column(name="content", length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="insert_ts", nullable=false, length=19)
    public Date getInsertTs() {
        return this.insertTs;
    }
    
    public void setInsertTs(Date insertTs) {
        this.insertTs = insertTs;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="linkType")
    public Integer getLinkType() {
        return this.linkType;
    }
    
    public void setLinkType(Integer linkType) {
        this.linkType = linkType;
    }

    
    @Column(name="mimeType", length=50)
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }




}


