/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name="privilege"
    
)
public class Privilege  implements java.io.Serializable {


     private Long id;
     private Proposal proposal;
     private Collaborationuser collaborationuser;
     private Discussiongroup discussiongroup;
     private Date fromDate;
     private Boolean mayChangeStatus;
     private Boolean mayManageObjects;
     private Boolean sendMail;

    public Privilege() {
    }

	
    public Privilege(Discussiongroup discussiongroup, Date fromDate) {
        this.discussiongroup = discussiongroup;
        this.fromDate = fromDate;
    }
    public Privilege(Proposal proposal, Collaborationuser collaborationuser, Discussiongroup discussiongroup, Date fromDate, Boolean mayChangeStatus, Boolean mayManageObjects, Boolean sendMail) {
       this.proposal = proposal;
       this.collaborationuser = collaborationuser;
       this.discussiongroup = discussiongroup;
       this.fromDate = fromDate;
       this.mayChangeStatus = mayChangeStatus;
       this.mayManageObjects = mayManageObjects;
       this.sendMail = sendMail;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proposalId")
    public Proposal getProposal() {
        return this.proposal;
    }
    
    public void setProposal(Proposal proposal) {
        this.proposal = proposal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="collaborationUserId")
    public Collaborationuser getCollaborationuser() {
        return this.collaborationuser;
    }
    
    public void setCollaborationuser(Collaborationuser collaborationuser) {
        this.collaborationuser = collaborationuser;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionGroupId")
    public Discussiongroup getDiscussiongroup() {
        return this.discussiongroup;
    }
    
    public void setDiscussiongroup(Discussiongroup discussiongroup) {
        this.discussiongroup = discussiongroup;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fromDate", nullable=false, length=19)
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    
    @Column(name="mayChangeStatus")
    public Boolean getMayChangeStatus() {
        return this.mayChangeStatus;
    }
    
    public void setMayChangeStatus(Boolean mayChangeStatus) {
        this.mayChangeStatus = mayChangeStatus;
    }
    
    @Column(name="mayManageObjects")
    public Boolean getMayManageObjects() {
        return this.mayManageObjects;
    }
    
    public void setMayManageObjects(Boolean mayManageObjects) {
        this.mayManageObjects = mayManageObjects;
    }
    
    @Column(name="sendMail")
    public Boolean getSendMail() {
        return this.sendMail;
    }
    
    public void setSendMail(Boolean sendMail) {
        this.sendMail = sendMail;
    }
}


