package de.fhdo.collaboration.db.classes;
// Generated 30.06.2015 09:32:45 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proposalstatuschange generated by hbm2java
 */
@Entity
@Table(name="proposalstatuschange"
    
)
public class Proposalstatuschange  implements java.io.Serializable {


     private Long id;
     private Collaborationuser collaborationuser;
     private Proposal proposal;
     private int proposalStatusFrom;
     private int proposalStatusTo;
     private Date changeTimestamp;
     private String reason;

    public Proposalstatuschange() {
    }

	
    public Proposalstatuschange(Collaborationuser collaborationuser, Proposal proposal, int proposalStatusFrom, int proposalStatusTo, Date changeTimestamp) {
        this.collaborationuser = collaborationuser;
        this.proposal = proposal;
        this.proposalStatusFrom = proposalStatusFrom;
        this.proposalStatusTo = proposalStatusTo;
        this.changeTimestamp = changeTimestamp;
    }
    public Proposalstatuschange(Collaborationuser collaborationuser, Proposal proposal, int proposalStatusFrom, int proposalStatusTo, Date changeTimestamp, String reason) {
       this.collaborationuser = collaborationuser;
       this.proposal = proposal;
       this.proposalStatusFrom = proposalStatusFrom;
       this.proposalStatusTo = proposalStatusTo;
       this.changeTimestamp = changeTimestamp;
       this.reason = reason;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="collaborationUserId", nullable=false)
    public Collaborationuser getCollaborationuser() {
        return this.collaborationuser;
    }
    
    public void setCollaborationuser(Collaborationuser collaborationuser) {
        this.collaborationuser = collaborationuser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proposalId", nullable=false)
    public Proposal getProposal() {
        return this.proposal;
    }
    
    public void setProposal(Proposal proposal) {
        this.proposal = proposal;
    }

    
    @Column(name="proposalStatusFrom", nullable=false)
    public int getProposalStatusFrom() {
        return this.proposalStatusFrom;
    }
    
    public void setProposalStatusFrom(int proposalStatusFrom) {
        this.proposalStatusFrom = proposalStatusFrom;
    }

    
    @Column(name="proposalStatusTo", nullable=false)
    public int getProposalStatusTo() {
        return this.proposalStatusTo;
    }
    
    public void setProposalStatusTo(int proposalStatusTo) {
        this.proposalStatusTo = proposalStatusTo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="changeTimestamp", nullable=false, length=19)
    public Date getChangeTimestamp() {
        return this.changeTimestamp;
    }
    
    public void setChangeTimestamp(Date changeTimestamp) {
        this.changeTimestamp = changeTimestamp;
    }

    
    @Column(name="reason", length=65535)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }




}


