package de.fhdo.collaboration.db.classes;
// Generated 30.06.2015 09:32:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Quote generated by hbm2java
 */
@Entity
@Table(name="quote"
    
)
public class Quote  implements java.io.Serializable {


     private Long id;
     private Discussion discussionByDiscussionId;
     private Discussion discussionByDiscussionIdQuoted;
     private String text;

    public Quote() {
    }

    public Quote(Discussion discussionByDiscussionId, Discussion discussionByDiscussionIdQuoted, String text) {
       this.discussionByDiscussionId = discussionByDiscussionId;
       this.discussionByDiscussionIdQuoted = discussionByDiscussionIdQuoted;
       this.text = text;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionId")
    public Discussion getDiscussionByDiscussionId() {
        return this.discussionByDiscussionId;
    }
    
    public void setDiscussionByDiscussionId(Discussion discussionByDiscussionId) {
        this.discussionByDiscussionId = discussionByDiscussionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionIdQuoted")
    public Discussion getDiscussionByDiscussionIdQuoted() {
        return this.discussionByDiscussionIdQuoted;
    }
    
    public void setDiscussionByDiscussionIdQuoted(Discussion discussionByDiscussionIdQuoted) {
        this.discussionByDiscussionIdQuoted = discussionByDiscussionIdQuoted;
    }

    
    @Column(name="text", length=65535)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


