package de.fhdo.collaboration.db.classes;
// Generated 30.06.2015 09:32:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name="rating"
    
)
public class Rating  implements java.io.Serializable {


     private Long id;
     private Collaborationuser collaborationuser;
     private Discussion discussion;
     private Proposal proposal;
     private Integer negative;
     private Integer positive;
     private String text;
     private Integer value;

    public Rating() {
    }

	
    public Rating(Collaborationuser collaborationuser) {
        this.collaborationuser = collaborationuser;
    }
    public Rating(Collaborationuser collaborationuser, Discussion discussion, Proposal proposal, Integer negative, Integer positive, String text, Integer value) {
       this.collaborationuser = collaborationuser;
       this.discussion = discussion;
       this.proposal = proposal;
       this.negative = negative;
       this.positive = positive;
       this.text = text;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="collaborationUserId", nullable=false)
    public Collaborationuser getCollaborationuser() {
        return this.collaborationuser;
    }
    
    public void setCollaborationuser(Collaborationuser collaborationuser) {
        this.collaborationuser = collaborationuser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionId")
    public Discussion getDiscussion() {
        return this.discussion;
    }
    
    public void setDiscussion(Discussion discussion) {
        this.discussion = discussion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proposalId")
    public Proposal getProposal() {
        return this.proposal;
    }
    
    public void setProposal(Proposal proposal) {
        this.proposal = proposal;
    }

    
    @Column(name="negative")
    public Integer getNegative() {
        return this.negative;
    }
    
    public void setNegative(Integer negative) {
        this.negative = negative;
    }

    
    @Column(name="positive")
    public Integer getPositive() {
        return this.positive;
    }
    
    public void setPositive(Integer positive) {
        this.positive = positive;
    }

    
    @Column(name="text", length=65535)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    
    @Column(name="value")
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }




}


