/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    
)
public class Role  implements java.io.Serializable {

     private Long id;
     private Boolean adminFlag;
     private String name;
     private Set<Status> statuses = new HashSet<Status>(0);
     private Set<Collaborationuser> collaborationusers = new HashSet<Collaborationuser>(0);
     private Set<Statusrel> statusrels = new HashSet<Statusrel>(0);

    public Role() {
    }

    public Role(Boolean adminFlag, String name, Set<Status> statuses, Set<Collaborationuser> collaborationusers, Set<Statusrel> statusrels) {
       this.adminFlag = adminFlag;
       this.name = name;
       this.statuses = statuses;
       this.collaborationusers = collaborationusers;
       this.statusrels = statusrels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="adminFlag")
    public Boolean getAdminFlag() {
        return this.adminFlag;
    }
    
    public void setAdminFlag(Boolean adminFlag) {
        this.adminFlag = adminFlag;
    }
    
    @Column(name="name", length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="role2status", joinColumns = { 
        @JoinColumn(name="roleId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="statusId", nullable=false, updatable=false) })
    public Set<Status> getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set<Status> statuses) {
        this.statuses = statuses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="role2collaborationuser", joinColumns = { 
        @JoinColumn(name="roleId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="collaborationUserId", nullable=false, updatable=false) })
    public Set<Collaborationuser> getCollaborationusers() {
        return this.collaborationusers;
    }
    
    public void setCollaborationusers(Set<Collaborationuser> collaborationusers) {
        this.collaborationusers = collaborationusers;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="role2action", joinColumns = { 
        @JoinColumn(name="roleId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="statusRelId", nullable=false, updatable=false) })
    public Set<Statusrel> getStatusrels() {
        return this.statusrels;
    }
    
    public void setStatusrels(Set<Statusrel> statusrels) {
        this.statusrels = statusrels;
    }




}


