package de.fhdo.collaboration.db.classes;
// Generated 30.06.2015 09:32:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Statusrel generated by hbm2java
 */
@Entity
@Table(name="statusrel"
    
)
public class Statusrel  implements java.io.Serializable {


     private Long id;
     private Action action;
     private Status statusByStatusIdTo;
     private Status statusByStatusIdFrom;
     private Set<Role> roles = new HashSet<Role>(0);

    public Statusrel() {
    }

	
    public Statusrel(Status statusByStatusIdTo, Status statusByStatusIdFrom) {
        this.statusByStatusIdTo = statusByStatusIdTo;
        this.statusByStatusIdFrom = statusByStatusIdFrom;
    }
    public Statusrel(Action action, Status statusByStatusIdTo, Status statusByStatusIdFrom, Set<Role> roles) {
       this.action = action;
       this.statusByStatusIdTo = statusByStatusIdTo;
       this.statusByStatusIdFrom = statusByStatusIdFrom;
       this.roles = roles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="actionId")
    public Action getAction() {
        return this.action;
    }
    
    public void setAction(Action action) {
        this.action = action;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="statusIdTo", nullable=false)
    public Status getStatusByStatusIdTo() {
        return this.statusByStatusIdTo;
    }
    
    public void setStatusByStatusIdTo(Status statusByStatusIdTo) {
        this.statusByStatusIdTo = statusByStatusIdTo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="statusIdFrom", nullable=false)
    public Status getStatusByStatusIdFrom() {
        return this.statusByStatusIdFrom;
    }
    
    public void setStatusByStatusIdFrom(Status statusByStatusIdFrom) {
        this.statusByStatusIdFrom = statusByStatusIdFrom;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="role2action", catalog="collab", joinColumns = { 
        @JoinColumn(name="statusRelId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="roleId", nullable=false, updatable=false) })
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }




}


