/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CodeSystemConcept generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement
@XmlType(namespace = "de.fhdo.termserver.types")
@Entity
@Table(name = "code_system_concept"
)
public class CodeSystemConcept implements java.io.Serializable
{

  private Long codeSystemEntityVersionId;
  private CodeSystemEntityVersion codeSystemEntityVersion;
  private String code;
  private String term;
  private String termAbbrevation;
  private String description;
  private Boolean isPreferred;
  private String meaning;
  private String hints;
  private Set<CodeSystemConceptTranslation> codeSystemConceptTranslations = new HashSet<CodeSystemConceptTranslation>(0);

  public CodeSystemConcept()
  {
  }

  public CodeSystemConcept(Long codeSystemEntityVersionId, CodeSystemEntityVersion codeSystemEntityVersion, String code, String term)
  {
    this.codeSystemEntityVersionId = codeSystemEntityVersionId;
    this.codeSystemEntityVersion = codeSystemEntityVersion;
    this.code = code;
    this.term = term;
  }

  public CodeSystemConcept(Long codeSystemEntityVersionId, CodeSystemEntityVersion codeSystemEntityVersion, String code, String term, String termAbbrevation, String description, Boolean isPreferred, Set<CodeSystemConceptTranslation> codeSystemConceptTranslations, String meaning, String hints)
  {
    this.codeSystemEntityVersionId = codeSystemEntityVersionId;
    this.codeSystemEntityVersion = codeSystemEntityVersion;
    this.code = code;
    this.term = term;
    this.termAbbrevation = termAbbrevation;
    this.description = description;
    this.isPreferred = isPreferred;
    this.codeSystemConceptTranslations = codeSystemConceptTranslations;
    this.meaning = meaning;
    this.hints = hints;
  }

  @Id

  @Column(name = "codeSystemEntityVersionId", unique = true, nullable = false)
  public Long getCodeSystemEntityVersionId()
  {
    return this.codeSystemEntityVersionId;
  }

  public void setCodeSystemEntityVersionId(Long codeSystemEntityVersionId)
  {
    this.codeSystemEntityVersionId = codeSystemEntityVersionId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "codeSystemEntityVersionId", unique = true, nullable = false, insertable = false, updatable = false)
  public CodeSystemEntityVersion getCodeSystemEntityVersion()
  {
    return this.codeSystemEntityVersion;
  }

  public void setCodeSystemEntityVersion(CodeSystemEntityVersion codeSystemEntityVersion)
  {
    this.codeSystemEntityVersion = codeSystemEntityVersion;
  }

  @Column(name = "code", nullable = false, length = 100)
  public String getCode()
  {
    return this.code;
  }

  public void setCode(String code)
  {
    this.code = code;
  }

  @Column(name = "term", nullable = false, length = 65535)
  public String getTerm()
  {
    return this.term;
  }

  public void setTerm(String term)
  {
    this.term = term;
  }

  @Column(name = "termAbbrevation", length = 50)
  public String getTermAbbrevation()
  {
    return this.termAbbrevation;
  }

  public void setTermAbbrevation(String termAbbrevation)
  {
    this.termAbbrevation = termAbbrevation;
  }

  @Column(name = "description", length = 65535)
  public String getDescription()
  {
    return this.description;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }

  @Column(name = "isPreferred")
  public Boolean getIsPreferred()
  {
    return this.isPreferred;
  }

  public void setIsPreferred(Boolean isPreferred)
  {
    this.isPreferred = isPreferred;
  }

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "codeSystemConcept")
  public Set<CodeSystemConceptTranslation> getCodeSystemConceptTranslations()
  {
    return this.codeSystemConceptTranslations;
  }

  public void setCodeSystemConceptTranslations(Set<CodeSystemConceptTranslation> codeSystemConceptTranslations)
  {
    this.codeSystemConceptTranslations = codeSystemConceptTranslations;
  }

  @Column(name = "meaning", length = 65535)
  public String getMeaning()
  {
    return meaning;
  }

  public void setMeaning(String meaning)
  {
    this.meaning = meaning;
  }

  @Column(name = "hints", length = 65535)
  public String getHints()
  {
    return hints;
  }

  public void setHints(String hints)
  {
    this.hints = hints;
  }
}
