/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domain generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlRootElement
@XmlType(namespace="de.fhdo.termserver.types")
@Entity
@Table(name="domain"
    
)
public class Domain  implements java.io.Serializable {


     private Long domainId;
     private String domainName;
     private String domainOid;
     private String description;
     private String displayText;
     private Boolean isOptional;
     private String defaultValue;
     private String domainType;
     private Long displayOrder;
     private Set<DomainValue> domainValues = new HashSet<DomainValue>(0);

    public Domain() {
    }

	
    public Domain(String domainName) {
        this.domainName = domainName;
    }
    public Domain(String domainName, String domainOid, String description, String displayText, Boolean isOptional, String defaultValue, String domainType, Long displayOrder, Set<DomainValue> domainValues) {
       this.domainName = domainName;
       this.domainOid = domainOid;
       this.description = description;
       this.displayText = displayText;
       this.isOptional = isOptional;
       this.defaultValue = defaultValue;
       this.domainType = domainType;
       this.displayOrder = displayOrder;
       this.domainValues = domainValues;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="domainId", unique=true, nullable=false)
    public Long getDomainId() {
        return this.domainId;
    }
    
    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }
    
    @Column(name="domainName", nullable=false, length=50)
    public String getDomainName() {
        return this.domainName;
    }
    
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }
    
    @Column(name="domainOid", length=50)
    public String getDomainOid() {
        return this.domainOid;
    }
    
    public void setDomainOid(String domainOid) {
        this.domainOid = domainOid;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="displayText", length=65535)
    public String getDisplayText() {
        return this.displayText;
    }
    
    public void setDisplayText(String displayText) {
        this.displayText = displayText;
    }
    
    @Column(name="isOptional")
    public Boolean getIsOptional() {
        return this.isOptional;
    }
    
    public void setIsOptional(Boolean isOptional) {
        this.isOptional = isOptional;
    }
    
    @Column(name="defaultValue", length=60)
    public String getDefaultValue() {
        return this.defaultValue;
    }
    
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }
    
    @Column(name="domainType", length=50)
    public String getDomainType() {
        return this.domainType;
    }
    
    public void setDomainType(String domainType) {
        this.domainType = domainType;
    }
    
    @Column(name="displayOrder")
    public Long getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Long displayOrder) {
        this.displayOrder = displayOrder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domain")
    public Set<DomainValue> getDomainValues() {
        return this.domainValues;
    }
    
    public void setDomainValues(Set<DomainValue> domainValues) {
        this.domainValues = domainValues;
    }




}


