/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TermUser generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlRootElement
@XmlType(namespace="de.fhdo.termserver.types")
@Entity
@Table(name="term_user"
    
)
public class TermUser  implements java.io.Serializable {


     private Long id;
     private String name;
     private String passw;
     private String email;
     private String salt;
     private boolean isAdmin;
     private boolean enabled;
     private String pseudonym;
     private String userName;
     private String activationMd5;
     private Date activationTime;
     private Set<Session> sessions = new HashSet<Session>(0);
     private Set<LicencedUser> licencedUsers = new HashSet<LicencedUser>(0);

    public TermUser() {
    }

	
    public TermUser(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public TermUser(String name, String passw, boolean isAdmin, String pseudonym, Set<Session> sessions, Set<LicencedUser> licencedUsers) {
       this.name = name;
       this.passw = passw;
       this.isAdmin = isAdmin;
       this.pseudonym = pseudonym;
       this.sessions = sessions;
       this.licencedUsers = licencedUsers;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="userName")
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="passw", length=65535)
    public String getPassw() {
        return this.passw;
    }
    
    public void setPassw(String passw) {
        this.passw = passw;
    }
    
    @Column(name="isAdmin", nullable=false)
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    
    @Column(name="pseudonym", length=100)
    public String getPseudonym() {
        return this.pseudonym;
    }
    
    public void setPseudonym(String pseudonym) {
        this.pseudonym = pseudonym;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="termUser")
    public Set<Session> getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Set<Session> sessions) {
        this.sessions = sessions;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="termUser")
    public Set<LicencedUser> getLicencedUsers() {
        return this.licencedUsers;
    }
    
    public void setLicencedUsers(Set<LicencedUser> licencedUsers) {
        this.licencedUsers = licencedUsers;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="activation_time", nullable=true, length=19)
    public Date getActivationTime() {
        return this.activationTime;
    }
    
    public void setActivationTime(Date activationTime) {
        this.activationTime = activationTime;
    }
    
    @Column(name="activation_md5")
    public String getActivationMd5() {
        return this.activationMd5;
    }
    
    public void setActivationMd5(String activationMd5) {
        this.activationMd5 = activationMd5;
    }
    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="salt")
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    
    
    @Column(name="enabled", nullable=false)
    public Boolean getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
}


