/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ValueSetVersion generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement
@XmlType(namespace = "de.fhdo.termserver.types")
@Entity
@Table(name = "value_set_version"
)
public class ValueSetVersion implements java.io.Serializable
{

  private Long versionId;
  private ValueSet valueSet;
  private Integer status;
  private Date statusDate;
  private Date insertTimestamp;
  private Date releaseDate;
  private Long previousVersionId;
  private String preferredLanguageCd;
  private String oid;
  private String name;
  private Long validityRange;
  private Date lastChangeDate;
  private Set<ConceptValueSetMembership> conceptValueSetMemberships = new HashSet<ConceptValueSetMembership>(0);

  public ValueSetVersion()
  {
  }

  public ValueSetVersion(ValueSet valueSet, Date statusDate, Date insertTimestamp)
  {
    this.valueSet = valueSet;
    this.statusDate = statusDate;
    this.insertTimestamp = insertTimestamp;
  }

  public ValueSetVersion(ValueSet valueSet, Integer status, Date statusDate, Date insertTimestamp, Date releaseDate, String name, Long previousVersionId, String preferredLanguageCd, String oid, Long validityRange, Date lastChangeDate, Set<ConceptValueSetMembership> conceptValueSetMemberships)
  {
    this.valueSet = valueSet;
    this.status = status;
    this.statusDate = statusDate;
    this.insertTimestamp = insertTimestamp;
    this.releaseDate = releaseDate;
    this.previousVersionId = previousVersionId;
    this.preferredLanguageCd = preferredLanguageCd;
    this.oid = oid;
    this.validityRange = validityRange;
    this.lastChangeDate = lastChangeDate;
    this.conceptValueSetMemberships = conceptValueSetMemberships;
    this.name = name;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)

  @Column(name = "versionId", unique = true, nullable = false)
  public Long getVersionId()
  {
    return this.versionId;
  }

  public void setVersionId(Long versionId)
  {
    this.versionId = versionId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "valueSetId", nullable = false)
  public ValueSet getValueSet()
  {
    return this.valueSet;
  }

  public void setValueSet(ValueSet valueSet)
  {
    this.valueSet = valueSet;
  }

  @Column(name = "name", nullable = false, length = 100)
  public String getName()
  {
    return this.name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  @Column(name = "status")
  public Integer getStatus()
  {
    return this.status;
  }

  public void setStatus(Integer status)
  {
    this.status = status;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "statusDate", nullable = false, length = 19)
  public Date getStatusDate()
  {
    return this.statusDate;
  }

  public void setStatusDate(Date statusDate)
  {
    this.statusDate = statusDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "lastChangeDate", length = 19)
  public Date getLastChangeDate()
  {
    return this.lastChangeDate;
  }

  public void setLastChangeDate(Date lastChangeDate)
  {
    this.lastChangeDate = lastChangeDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "insertTimestamp", nullable = false, length = 19)
  public Date getInsertTimestamp()
  {
    return this.insertTimestamp;
  }

  public void setInsertTimestamp(Date insertTimestamp)
  {
    this.insertTimestamp = insertTimestamp;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "releaseDate", length = 19)
  public Date getReleaseDate()
  {
    return this.releaseDate;
  }

  public void setReleaseDate(Date releaseDate)
  {
    this.releaseDate = releaseDate;
  }

  @Column(name = "previousVersionId")
  public Long getPreviousVersionId()
  {
    return this.previousVersionId;
  }

  public void setPreviousVersionId(Long previousVersionId)
  {
    this.previousVersionId = previousVersionId;
  }

  @Column(name = "preferredLanguageCd")
  public String getPreferredLanguageCd()
  {
    return this.preferredLanguageCd;
  }

  public void setPreferredLanguageCd(String preferredLanguageCd)
  {
    this.preferredLanguageCd = preferredLanguageCd;
  }

  @Column(name = "oid", length = 100)
  public String getOid()
  {
    return this.oid;
  }

  public void setOid(String oid)
  {
    this.oid = oid;
  }

  @Column(name = "validityRange")
  public Long getValidityRange()
  {
    return this.validityRange;
  }

  public void setValidityRange(Long validityRange)
  {
    this.validityRange = validityRange;
  }

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "valueSetVersion")
  public Set<ConceptValueSetMembership> getConceptValueSetMemberships()
  {
    return this.conceptValueSetMemberships;
  }

  public void setConceptValueSetMemberships(Set<ConceptValueSetMembership> conceptValueSetMemberships)
  {
    this.conceptValueSetMemberships = conceptValueSetMemberships;
  }

}
