/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.terminologie.db.hibernate;
// Generated 24.10.2011 10:08:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ValueSet generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlRootElement
@XmlType(namespace="de.fhdo.termserver.types")
@Entity
@Table(name="value_set"
    
)
public class ValueSet  implements java.io.Serializable {


     private Long id;
     private Long currentVersionId;
     private String name;
     private String description;
     private String descriptionEng;
     private Integer status;
     private Date statusDate;
     private String website;
     private Set<ValueSetVersion> valueSetVersions = new HashSet<ValueSetVersion>(0);
     private Set<MetadataParameter> metadataParameters = new HashSet<MetadataParameter>(0);

    public ValueSet() {
    }

    public ValueSet(Long currentVersionId, String name, String description, String descriptionEng, String website, Integer status, Date statusDate, Set<ValueSetVersion> valueSetVersions) {
       this.currentVersionId = currentVersionId;
       this.name = name;
       this.description = description;
       this.status = status;
       this.statusDate = statusDate;
       this.valueSetVersions = valueSetVersions;
       this.website = website;
       this.descriptionEng = descriptionEng;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="currentVersionId")
    public Long getCurrentVersionId() {
        return this.currentVersionId;
    }
    
    public void setCurrentVersionId(Long currentVersionId) {
        this.currentVersionId = currentVersionId;
    }
    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Column(name="descriptionEng", length=65535)
    public String getDescriptionEng() {
        return this.descriptionEng;
    }
    
    public void setDescriptionEng(String descriptionEng) {
        this.descriptionEng = descriptionEng;
    }
    
    @Column(name = "website", length = 65535)
    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="statusDate", length=19)
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="valueSet")
    public Set<ValueSetVersion> getValueSetVersions() {
        return this.valueSetVersions;
    }
    
    public void setValueSetVersions(Set<ValueSetVersion> valueSetVersions) {
        this.valueSetVersions = valueSetVersions;
    }

@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "valueSet")
  public Set<MetadataParameter> getMetadataParameters()
  {
    return this.metadataParameters;
  }

  public void setMetadataParameters(Set<MetadataParameter> metadataParameters)
  {
    this.metadataParameters = metadataParameters;
  }


}


