/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Discussiongroup generated by hbm2java
 */
@Entity
@Table(name="discussiongroup"
    
)
public class Discussiongroup  implements java.io.Serializable {


     private Long id;
     private String name;
     private Long head;
     private Set<Discussiongroupobject> discussiongroupobjects = new HashSet<Discussiongroupobject>(0);
     private Set<Collaborationuser> collaborationusers = new HashSet<Collaborationuser>(0);
     private Set<Privilege> privileges = new HashSet<Privilege>(0);

    public Discussiongroup() {
    }

	
    public Discussiongroup(String name) {
        this.name = name;
    }
    public Discussiongroup(String name, Long head, Set<Discussiongroupobject> discussiongroupobjects, Set<Collaborationuser> collaborationusers, Set<Privilege> privileges) {
       this.name = name;
       this.head = head;
       this.discussiongroupobjects = discussiongroupobjects;
       this.collaborationusers = collaborationusers;
       this.privileges = privileges;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="head")
    public Long getHead() {
        return this.head;
    }
    
    public void setHead(Long head) {
        this.head = head;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="discussiongroup")
    public Set<Discussiongroupobject> getDiscussiongroupobjects() {
        return this.discussiongroupobjects;
    }
    
    public void setDiscussiongroupobjects(Set<Discussiongroupobject> discussiongroupobjects) {
        this.discussiongroupobjects = discussiongroupobjects;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="discussiongroup2collaborationuser", joinColumns = { 
        @JoinColumn(name="discussionGroupId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="collaborationuserId", nullable=false, updatable=false) })
    public Set<Collaborationuser> getCollaborationusers() {
        return this.collaborationusers;
    }
    
    public void setCollaborationusers(Set<Collaborationuser> collaborationusers) {
        this.collaborationusers = collaborationusers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="discussiongroup")
    public Set<Privilege> getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(Set<Privilege> privileges) {
        this.privileges = privileges;
    }
}


