/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proposalstatuschange generated by hbm2java
 */
@Entity
@Table(name="proposalstatuschange"
    
)
public class Proposalstatuschange  implements java.io.Serializable {


     private Long id;
     private Proposal proposal;
     private Collaborationuser collaborationuser;
     private int proposalStatusFrom;
     private int proposalStatusTo;
     private Date changeTimestamp;
     private String reason;

    public Proposalstatuschange() {
    }

	
    public Proposalstatuschange(Proposal proposal, Collaborationuser collaborationuser, int proposalStatusFrom, int proposalStatusTo, Date changeTimestamp) {
        this.proposal = proposal;
        this.collaborationuser = collaborationuser;
        this.proposalStatusFrom = proposalStatusFrom;
        this.proposalStatusTo = proposalStatusTo;
        this.changeTimestamp = changeTimestamp;
    }
    public Proposalstatuschange(Proposal proposal, Collaborationuser collaborationuser, int proposalStatusFrom, int proposalStatusTo, Date changeTimestamp, String reason) {
       this.proposal = proposal;
       this.collaborationuser = collaborationuser;
       this.proposalStatusFrom = proposalStatusFrom;
       this.proposalStatusTo = proposalStatusTo;
       this.changeTimestamp = changeTimestamp;
       this.reason = reason;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proposalId", nullable=false)
    public Proposal getProposal() {
        return this.proposal;
    }
    
    public void setProposal(Proposal proposal) {
        this.proposal = proposal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="collaborationUserId", nullable=false)
    public Collaborationuser getCollaborationuser() {
        return this.collaborationuser;
    }
    
    public void setCollaborationuser(Collaborationuser collaborationuser) {
        this.collaborationuser = collaborationuser;
    }
    
    @Column(name="proposalStatusFrom", nullable=false)
    public int getProposalStatusFrom() {
        return this.proposalStatusFrom;
    }
    
    public void setProposalStatusFrom(int proposalStatusFrom) {
        this.proposalStatusFrom = proposalStatusFrom;
    }
    
    @Column(name="proposalStatusTo", nullable=false)
    public int getProposalStatusTo() {
        return this.proposalStatusTo;
    }
    
    public void setProposalStatusTo(int proposalStatusTo) {
        this.proposalStatusTo = proposalStatusTo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="changeTimestamp", nullable=false, length=19)
    public Date getChangeTimestamp() {
        return this.changeTimestamp;
    }
    
    public void setChangeTimestamp(Date changeTimestamp) {
        this.changeTimestamp = changeTimestamp;
    }
    
    @Column(name="reason", length=65535)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }




}


