/* 
 * CTS2 based Terminology Server and Terminology Browser
 * Copyright (C) 2014 FH Dortmund: Peter Haas, Robert Muetzner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fhdo.collaboration.db.classes;
// Generated 15.05.2013 18:02:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Quote generated by hbm2java
 */
@Entity
@Table(name="quote"
    
)
public class Quote  implements java.io.Serializable {


     private Long id;
     private Discussion discussionByDiscussionId;
     private Discussion discussionByDiscussionIdQuoted;
     private String text;

    public Quote() {
    }

    public Quote(Discussion discussionByDiscussionId, Discussion discussionByDiscussionIdQuoted, String text) {
       this.discussionByDiscussionId = discussionByDiscussionId;
       this.discussionByDiscussionIdQuoted = discussionByDiscussionIdQuoted;
       this.text = text;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionId")
    public Discussion getDiscussionByDiscussionId() {
        return this.discussionByDiscussionId;
    }
    
    public void setDiscussionByDiscussionId(Discussion discussionByDiscussionId) {
        this.discussionByDiscussionId = discussionByDiscussionId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="discussionIdQuoted")
    public Discussion getDiscussionByDiscussionIdQuoted() {
        return this.discussionByDiscussionIdQuoted;
    }
    
    public void setDiscussionByDiscussionIdQuoted(Discussion discussionByDiscussionIdQuoted) {
        this.discussionByDiscussionIdQuoted = discussionByDiscussionIdQuoted;
    }
    
    @Column(name="text", length=65535)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


